### PR TITLE
ASM-5449 Import Config XML for server having both Intel and Broadcom nic failing

### PR DESCRIPTION
**Pull request by sushilrai**
Updated XPath for searching the attribute. Now checking in specific FQDD for the attributes that needs to be skipped for Intel NICS

### CODE REVIEW

**Comment by sushilrai** [comment]
@gavin-scott CI tests are failing while installing dell-asm-util package. 

https://travis-ci.org/dell-asm/dell-idrac/jobs/97396739#L174

**Comment by sushilrai** [comment]
@gavin-scott can you please take a look into this. Tests are failing while downloading the dell-asm-utils gem

**Comment by sushilrai** [comment]
@ripienaar can you please look into this. Tests are failing while installing dell-asm-util gem

**Comment by ripienaar** [comment]
I'll check tonight or morrow first thing

**Comment by gavin-scott** [comment]
I can look at this. Not sure what's up with travis not getting dell-asm-util checked out, but the tests are failing for me when I run locally. Looks like it's due to changes I made in dell-asm-util: https://github.com/dell-asm/dell-asm-util/pull/10

**Comment by gavin-scott** [comment]
Confirmed manually that the test failures here will be resolved by https://github.com/dell-asm/dell-idrac/pull/179 Going ahead and merging.

**Pull request merged**
