### PR TITLE
Merge 8.3.1 changes into master

### PR DESCRIPTION
**Pull request by gavin-scott**

### CODE REVIEW

**Comment by ripienaar** [comment]
@gavin-scott happy to merge these, just checking if you're ready for me to do so?

**Comment by gavin-scott** [comment]
Yes please @ripienaar go ahead ande merge. I'm never sure whether we should require review of merge PRs or just merge them, what do you think?

**Comment by ripienaar** [comment]
@gavin-scott happy to self merge them - all already reviewed code, small chance there are integration issues should master go ahead of the rest but I doubt a review will spot it when its a lot of code

**Comment by gavin-scott** [comment]
I agree, thanks @ripienaar I'll merge these.

**Pull request merged**
